# Generated by Django 4.2 on 2025-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Ave', 'Ave'), ('Hamster', 'Hamster'), ('Otro', 'Otro')], default='Perro', max_length=20),
        ),
    ]
